config/routes.rb
SampleApp::Application.routes.draw do
  resources :locations
  resources :user
  

  get "pages/home"
  get "pages/contact"
  get "pages/about"

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :address, :latitude, :longitude
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
  acts_as_gmappable
  def gmaps4rails_address
  :address
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
 
 
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

    before_filter :userip

    def userip
      @coords = request.location.coordinates
      @konta = Geocoder.search(@coords)
    end 
  
  # GET /locations
  # GET /locations.json
  def index
  
    @locations = Location.all
    @json = Location.all.to_gmaps4rails

    
 
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact Us"
  end

def about 
end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  
  def index
     @client = Geocoder.search(request.ip)
     @city = request.location.city
     @ip_address = request.ip
    @s = request.location.coordinates
    @konta = Location.near(@s)
     
     respond_to do |format|
       format.html # index.html.erb
       format.json { render json: @client}
     end
    end

 
  end
  

app/helpers/application_helper.rb
module ApplicationHelper

#Return a title on a per-page basis
def title
  base_title = "Ruby on Rails Tutorial App"
  if @title.nil? 
    base_title
else
  "#{base_title} | #{@title}"
end
end

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
	<title> <%= @title %> </title>


	<!--[if lt IE 9]>
	<script src = "http://html5shiv.googlecode.com/svn/trunk/html5.js"> </script>
	<! [endif] -->
	
	<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
	<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
	<!-- [if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><! [endif] -->
	<%= stylesheet_link_tag 'custom', :media => 'screen' %>
	<%= javascript_include_tag :defaults %>
		<%= csrf_meta_tag %>
	</head>
	<body>
		<div class ="container">
			<header>
				<%= image_tag("rails.png", :alt => 'Sample.png', :class => "round") %>
		<nav class="round">
			<ul>
				<li><%= link_to "Home", '#'%></li>
				<li><%= link_to "About", '#'%></li>
				</ul>
				</nav>
				</header>
		<section class = "round">
		<%= yield %>
		</section>
		</div>
		</body>
		<%= yield :scripts %>
		</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <tr>
    <th>Address</th>
    <th>Longitude</th>
    <th>Latitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.address %></td>
    <td><%= location.longitude %></td>
    <td><%= location.latitude %></td>
    <td><%= link_to 'Show', location %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<%= gmaps4rails(@json) %>


<%= link_to 'New Location', new_location_path %>

<%= @user %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Address:</b>
  <%= @location.address %>
</p>

<p>
  <b>Longitude:</b>
  <%= @location.longitude %>
</p>

<p>
  <b>Latitude:</b>
  <%= @location.latitude %>
</p>

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>


<h2>GMAPS4RAILS </h2>
<%= gmaps4rails(@json) %>
<h3> Ιατρεία κοντά σε <%= @location.address %> και <%= @city %> kai thesi <%= @coords %></h3>
<ul>
	
		<% for location in Location.near(@coords, 4) %>
		<li>
			<%= link_to location.address, location %> <%= location.distance.round(2) %> 
			</li>
		<% end %>
		
		</ul>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/pages/about.html.erb
<h1> Pages#about </h1>
<p> Find me in app/views/pages/about.html.erb </p>

app/views/pages/contact.html.erb
		<h1>Contact</h1>
		<p> Poutses Ble</p>
		

app/views/pages/home.html.erb
	<h1> Sample App </h1>
	<p> This is the home page from the Pages Controller </p>
	
	<%= link_to "Sign up now!", '#', :class => "signup_button round" %>

app/views/user/index.html.erb
your city is <%= @city %>
Your ip is <%= @ip_address %>
Your coords are <%= @s %>
Konta exei <%= @konta %>

app/views/user/show.html.erb
your ip is <%= @client_ip %>